- hosts: localhost
  tasks:
  - name: Ansible register variable basic example
    shell: "find *.txt"
    args:
      chdir: "test"
    register: find_output

  - shell: "cp {{ item }} {{item}}_bkp"
    with_items:
      - "{{ with_output.stdout_lines }}"
      
