
- hosts: all
  vars: 
    packagename: httpd 
  tasks:
    - debug:
             msg: "{{ packagename }}"
    - yum: name={{packagename}} state=present
    - service: name={{packagename}} enable=yes state=started	
