---
# tasks file for abhinav
- yum: name={{packagename}} state=present
  when: ansible_os_family == "RedHat"
- service: name=httpd enabled=yes state=started
  when: ansible_os_family == "RedHat"
- template:
    src: templates/httpd.j2
    dest: /etc/httpd/conf/httpd.conf
#- script= files/random.sh

#     - debug: var=ps.stdout_lines
- name: create group
  group: name=deloitte

- name: create user
  user: name=deploy

- name: Install common software requirements
  yum: name={{ item }} state=present
  with_items:
     - git
     - ntp
     - vim
